FROM continuumio/miniconda3:4.10.3p0 

RUN conda install -y -c conda-forge mamba
RUN mamba install -y -c conda-forge jupyterhub pip

ARG NB_USER=jovyan
ARG NB_UID=1000
ARG HOME=/home/jovyan

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    --home ${HOME} \
    --force-badname \
    ${NB_USER}

COPY ./zero-to-jupyterhub-k8s/images/hub/requirements.txt /tmp/requirements.txt
RUN pip3 install --upgrade --no-cache-dir \
        setuptools \
        pip
RUN PYCURL_SSL_LIBRARY=openssl \
    pip install --no-cache-dir \
        -r /tmp/requirements.txt

# Install bioturingauth
COPY ./bioturingauth /src/bioturingauth
WORKDIR /src/bioturingauth
RUN python3 setup.py install

# Install kubespawner 
COPY ./kubespawner /src/kubespawner
WORKDIR /src/kubespawner
RUN pip install ./


# Install a local jupyterhub repo
COPY . /src/jupyterhub
WORKDIR /src/jupyterhub
RUN pip install .

RUN mkdir -p /srv/jupyterhub
# So we can actually write a db file here
RUN chown ${NB_USER}:${NB_USER} /srv/jupyterhub
WORKDIR /srv/jupyterhub

# JupyterHub API port
EXPOSE 8081

# when building the dependencies image
# add pip-tools necessary for computing dependencies
# this is not done in production builds by chartpress
ARG PIP_TOOLS=
RUN test -z "$PIP_TOOLS" || pip install --no-cache pip-tools==$PIP_TOOLS

USER ${NB_USER}
CMD ["jupyterhub", "--config", "/usr/local/etc/jupyterhub/jupyterhub_config.py"]
